name: frontend
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.1.0
  shared_preferences: ^2.2.2
  badges: ^2.0.3
  provider: ^6.1.5+1
  image_picker: ^1.0.4
  photo_manager: 3.7.1
  permission_handler: ^11.0.1
  image: ^4.0.17

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: KyivTypeSerif
      fonts:
        - asset: assets/fonts/KyivTypeSerif-Light.ttf
          weight: 300
        - asset: assets/fonts/KyivTypeSerif-Regular.ttf
          weight: 400
        - asset: assets/fonts/KyivTypeSerif-Medium.ttf
          weight: 500
        - asset: assets/fonts/KyivTypeSerif-Bold.ttf
          weight: 700
